url: http://ailab-nav-mike.c9users.io
authorized_locales: ['en', 'ru']
default_locale: ru

#posts
permalink: /:categories/blog/:year/:month/:day/:title
excerpt_separator: <!--more-->

exclude: [_site, dockerfile]

gems: [RedCloth]
